development:
  adapter: postgresql
  database: db/dev
  pool: 5
  timeout: 5000
  password:

test:
  adapter: postgresql
  database: db/test
  pool: 5
  timeout: 5000
  password:

production:
  adapter: postgresql
  database: db/prod
  pool: 5
  timeout: 5000
  password:
