development:
  adapter: mysql2
  database: cc_dev
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock
  timeout: 5000
  pool: 5

test:
  adapter: mysql2
  database: cc_test
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock
  timeout: 5000
  pool: 5

production:
  adapter: mysql2
  database: cc_prod
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock
  timeout: 5000
  pool: 5